language: node_js
node_js:
  - 0.11
  - 0.10
  - 0.8
branches:
  only:
    - master
script: brunch test
before_script:
  - npm install -g bower brunch mocha-phantom
  - bower install
notifications:
  email: false
